spring.datasource.url=jdbc:mysql://herramientasdevops.conjjt9tcqoq.us-east-1.rds.amazonaws.com:3306/Sucursal?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
spring.datasource.username=admin
spring.datasource.password=OracleCloud2025
springdoc.api-docs.path=/api-docs
